
spring:
  devtools:
    livereload:
      enabled: true
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}


logging:
  level:
    '[org.springframework.security]': trace

selflearntech:
    trace: true
